name: All Jobs Completed

on:
  workflow_dispatch:

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Job One Step One
        run: |
          echo Run Job One Step One
  
  job-two:
    runs-on: ubuntu-latest
    steps:
      - name: Job Two Step One
        run: |
          echo Run Two One Step One

  job-three:
    runs-on: ubuntu-latest
    steps:
      - name: Job Three Step One
        run: |
          exit 1

  job-four:
    runs-on: ubuntu-latest
    steps:
      - name: Job Four Step One
        run: |
          echo Run Four One Step One

  wait-for-all:
    name: All jobs completed
    runs-on: ubuntu-latest
    needs:
      - job-one
      - job-two
      - job-three
      - job-four
    if: always()
    steps:
      - run: echo "All dependent jobs have completed."
