name: RE Caller 

on:
  workflow_dispatch:
    
jobs:
  run-inner-task:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Perform ECHO
        run: |
          echo "This is the end"
          echo "My friend, the end"

  call-wf-from-file:
    uses: ./.github/workflows/re_one.yaml
