name: Concurency 02

on:
  workflow_dispatch:

jobs:
  display_context:
    runs-on: ubuntu-latest
    steps:
          - name: Display Contexts
            run: | 
              echo I finished at $(date +%s)
