name: Create PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp
        run: |
          echo "Timestamp: $(date +%s)" > timestamp.txt
          git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update timestamp
          title: Update TIMESTAMP
          body: Credit new contributors by updating TIMESTAMP
          branch: update-timestamp
