name: Custom VAR yaml

on: push

jobs:
  set_and_use_env_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: |-
          echo myValue > _MY_ENV_VAR
          echo "MY_ENV_VAR=$(cat _MY_ENV_VAR)" >> $GITHUB_ENV

      - name: Set second variable derived from first
        run: |-
          echo VAR2=$(echo ${MY_ENV_VAR}) >> $GITHUB_ENV

      - name: Use environment variable
        run: |-
          echo "The value of MY_ENV_VAR is $(echo ${MY_ENV_VAR})"
          echo "The value of VAR2 is $(echo ${VAR2})"

      - name: List variables and values
        run: |-
          echo MY_ENV_VAR: ${{ env.MY_ENV_VAR }}
          echo VAR2: ${{ env.VAR2 }}
          test -n ${{ env.VAR2 }} || echo "The VAR2 is not setup"

