name: Display Contexts

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'
  pull_request:

jobs:
  display_context:
    runs-on: ubuntu-latest
    steps:
      - name: Display Contexts
        run: | 
          echo "GitHub SHA github.sha: ${{ github.sha }}"
          echo "GitHub Ref Name github.ref_name: ${{ github.ref_name }}"
          echo "GitHub Event Pull Reqeust Head github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"
          # only available when the event that triggers a workflow run is either pull_request or pull_request_target.
          echo "GitHub Base Ref (pr target branch) github.base_ref: ${{ github.base_ref }}"
          echo "GitHub Head Ref (source branch) github.head_ref: ${{ github.head_ref }}"
          echo ""
          echo "GIT_COMMIT=${{ github.event.pull_request.head.sha || github.sha }}"
          echo "When merging to master the GIT_COMMIT should be equal to github.sha"

  test-checkout:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
        timeout-minutes: 1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: list
        run: |
          pwd
          git branch
          ls -la 
      - id: three
        run: |
          echo Test this line too

