name: Build golang base image
# Zero change

on:
  workflow_dispatch:
  # workflow_call:
  # pull_request:
  # push:
  #   branches:
  #     - 'master'

# on:
#   workflow_call:
#     inputs:
#       sha:
#         description: 'SHA of the commit to build'
#         required: true
#         type: string
#       force:
#         description: 'Force build base images'
#         required: false
#         default: false
#         type: boolean
#       base_sha:
#         description: 'Base SHA for diff (optional)'
#         required: false
#         type: string
#         default: ${{ github.event.before }}
#     secrets:
#       GCP_SERVICE_ACCOUNT:
#         required: true

env:
  BUILD_SHA: ${{ github.sha }}

jobs:
  # Base image: Golang (1.24.6)
  images-golang-1-24-6:
    outputs:
      tag_exist: ${{ steps.tag_exist.outputs.TAG_EXIST }}
    env:
      Registry: yyovkov
      Image: golang
      BaseTag: 1.24.6
    strategy:
      matrix:
        platform:
          - linux/arm64
          - linux/amd64
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Prepare Multiplatform
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        timeout-minutes: 1
        with:
          ref: ${{ env.BUILD_SHA }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DEV_DOCKERHUB_USER }}
          password: ${{ secrets.DEV_DOCKERHUB_PAT }}

      # Adding this line for zero-change test
      - name: Push prod image
        id: build
        timeout-minutes: 20
        if: ${{ (steps.tag_exist.outputs.TAG_EXIST  == 'false') || (inputs.force == true)  }}
        uses: docker/build-push-action@v5
        with:
          context: images/golang/1.24.6
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.Registry }}/${{ env.Image }}:${{ env.BaseTag }}-${{ github.sha }}
            ${{ github.ref == 'refs/heads/master' && format('{0}/{1}:{2}', env.Registry, env.Image, env.BaseTag) || '' }}
