name: JOB DBT (manual)

on:
  workflow_dispatch:
    inputs:
      DBT_COMMAND:
        description: "Command to run"
        required: true

jobs:
  run-dbt-command:
    name: "Run DBT command"
    runs-on: ubuntu-latest
    steps:
      - name: 'Run Command'
        shell: bash
        run: |
          pwd
          ls -l 
          eval ${{ github.event.inputs.DBT_COMMAND }}

      - name: 'Run in docker'
        uses: docker://ubuntu
        with:
          run: eval ${{ github.event.inputs.DBT_COMMAND }}

