name: JOB DBT (manual)

on:
  workflow_dispatch:
    inputs:
      DBT_COMMAND:
        description: "Command to run"
        required: true
        type: string
      DOCKER_IMAGE_TAG:
        description: "dwh-analytics docker image tag"
        required: false
        default: latest

jobs:
  execute:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 1
      - name: "Running in a container"
        run: |
          hostname
          echo DOCKER_IMAGE_TAG is: ${{ github.event.inputs.DOCKER_IMAGE_TAG }}
          eval ${{ github.event.inputs.DBT_COMMAND }}
