name: JOB DBT (manual)

on:
  workflow_dispatch:
    inputs:
      DBT_COMMAND:
        description: "Command to run"
        required: true
        type: string

jobs:
  generate-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 1
      - name: Generate artifact
        shell: bash
        run: |
          echo "The command is: ${{ github.event.inputs.DBT_COMMAND }}" > my_artifact.txt

  use-artifact-in-docker:
    needs: [generate-artifact]
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - name: "Running in a container"
        run: |
          ls -l /.dockerenv
          hostname
          ls -l
          echo "Run DBT_COMMAND below:"
          eval ${{ github.event.inputs.DBT_COMMAND }}
