name: JOB DBT (manual)

on:
  workflow_dispatch:
    inputs:
      DBT_COMMAND:
        description: "Command to run"
        required: true

jobs:
  run-dbt-command:
    name: "Run DBT command"
    runs-on: ubuntu-latest
    container:
      image: nginx
    steps:
      - name: 'Run Command'
        shell: bash
        run: |
          echo The command is: ${{ github.event.inputs.DBT_COMMAND }}
          eval "${{ github.event.inputs.DBT_COMMAND }}"
          echo The command is: '${{ github.event.inputs.DBT_COMMAND }}'
