name: JOB DBT (manual)

on:
  workflow_dispatch:
    inputs:
      DBT_COMMAND:
        description: "Command to run"
        required: true

jobs:
  generate-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Generate artifact
        shell: bash
        run: |
          echo "This is the file content" > my_artifact.txt
          echo "The command is: ${{ github.event.inputs.DBT_COMMAND }}

  use-artifact-in-docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - name: "Running in a container"
        run: |
          ls -l /.dockerenv
          hostname
