name: Reusable workflow One

on:
  workflow_call:
    secrets:
      envPAT:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: display conig path
        with:
          repo-token: ${{ secrets.envPAT }}
        run: |
          echo CONFIG PATH: ${{ repo-token }}
