name: Reusable workflow One

on:
  workflow_call:
    secrets:
      envPAT:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: display conig path
        run: |
          echo ENV PATH secret: 
          base64 ${{ secrets.envPAT }} | bas64
