name: Reusable Workflow with Input

on:
  workflow_dispatch:
    inputs:
      var-to-pass:
        description: "Variable passed to the workflow"
        required: true
        type: string
  workflow_call:
    inputs:
      var-to-pass:
        description: "Variable passed to the workflow"
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: display conig path
        run: |
          echo CONFIG PATH: ${{ inputs.var-to-pass }}

