name: Reusable workflow One

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: display conig path
        run: |
          echo CONFIG PATH: ${{ inputs.config-path }}

