name: Build Base Images (reusable)

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  display_context:
    runs-on: self-hosted
    steps:
      - name: Display Contexts
        run: | 
          echo "GitHub SHA github.sha: ${{ github.sha }}"
          echo "GitHub Ref Name github.ref_name: ${{ github.ref_name }}"
          echo "GitHub Event Pull Reqeust Head github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"
          # only available when the event that triggers a workflow run is either pull_request or pull_request_target.
          echo "GitHub Base Ref (pr target branch) github.base_ref: ${{ github.base_ref }}"
          echo "GitHub Head Ref (source branch) github.head_ref: ${{ github.head_ref }}"
          echo ""
          echo "GIT_COMMIT=${{ github.event.pull_request.head.sha || github.sha }}"
          echo "When merging to master the GIT_COMMIT should be equal to github.sha"
          echo ""
          echo "Adding whitespace commit for feat/my-feature-02 branch"

      - uses: actions/checkout@v4
        timeout-minutes: 1
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        timeout-minutes: 1
        uses: docker/setup-buildx-action@v3
      
      - name: Set up Docker Buildx
        timeout-minutes: 1
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DEV_DOCKERHUB_USER }}
          password: ${{ secrets.DEV_DOCKERHUB_PAT }}

      - name: Build and push docker image
        timeout-minutes: 15
        uses: docker/build-push-action@v5
        with:
          context: images/test
          push: true
          # temp workaround for newer buildx where images outputed by default are not cloud run compatible https://github.com/docker/buildx/issues/1533
          provenance: false
          build-args: GIT_COMMIT=${{ github.event.pull_request.head.sha || github.sha }}
          tags: |
            ${{ github.event.pull_request.head.sha == null && 'yyovkov/test:3.11.8' || null }}
            yyovkov/test:3.11.8-${{ github.event.pull_request.head.sha || github.sha }}
          cache-from: |
            type=gha,scope=images/python/3.11.8/${{ github.ref_name }}
            type=registry,ref=europe-west1-docker.pkg.dev/triple-management/cache/python/3.11.8:newest
            type=${{ github.event.pull_request.head.sha == '' && 'registry,ref=europe-west1-docker.pkg.dev/myproject/cache/python/3.11.8:latest' || 'gha,scope=images/python/3.11.8/' + github.base_ref }}
          cache-to: |
            type=${{ github.event.pull_request.head.sha == null
              && 'type=registry,ref=europe-west1-docker.pkg.dev/triple-management/cache/python/3.11.8:latest,mode=max'
              || null
            }}
            type=registry,ref=europe-west1-docker.pkg.dev/triple-management/cache/python/3.11.8:newest,mode=max
            type=inline
