name: Rebuild Base Docker Images Weekly

on:
  schedule:
    - cron: '30 15 * * *'
  workflow_dispatch:
    
jobs:
  weekly:
    name: Rebuild Base Images
    uses: ./.github/workflows/re_build_image.yaml
