name: Substring Example

on:
  workflow_dispatch:

env:
   IMAGE_COMMIT_API: repo=europe-west1-docker.pkg.dev/triple-management/triple/api

jobs:
  test-substring:
    runs-on: ubuntu-latest
    steps:
      - name: Extract substring
        run: |
          _full_repo=${{ env.IMAGE_COMMIT_API }}
          _repo=${_full_repo%/*}
          _image=${_full_repo##*/}
          echo "DOCKER_REPO=${_full_repo%/*}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=${_full_repo##/*}" >> $GITHUB_ENV
          echo "REPO: ${_repo}"
          echo "IMAGE: ${_image}"
          echo "REPO (from env): ${{ env.DOCKER_REPO }}
          echo "IMAGE (from env): ${{ env.DOCKER_IMAGE }}
