name: Time triggered

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

env:
  BUILD_SHA: ${{ github.sha }}

jobs:
  build-docker-base-images:
    name: Build Docker Images
    uses: ./.github/workflows/workflow_run_03.yml
    with:
      sha: ${{ github.sha }}
    secrets:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
