name: Time triggered

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  my_scheduled_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run a script
        run: date
