name: Reusable Workflow with Input

on:
  workflow_call:
    inputs:
      sha:
        description: 'SHA ref to build'
        required: true
        type: string
      base_sha:
        description: 'Base SHA for diff (optional)'
        required: false
        type: string
        default: ${{ github.event.before }}
      force:
        description: 'Force build images'
        required: false
        default: false
        type: boolean

env:
  BUILD_SHA: ${{ inputs.sha }}

jobs:
  show-payload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJson(github) }}'
  
  display-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Display variables
        run: |
          echo "BUILD_SHA (input.sha): ${{ env.BUILD_SHA }}"
          echo "BASE_SHA (inputs.base_sha): ${{ inputs.base_sha }}"
          
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      images: ${{ steps.filter.outputs.images }}
      mtellb: ${{ steps.filter.outputs.metallb }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BUILD_SHA }}

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: .github/filters.yml
          base: ${{ inputs.base_sha }}
          ref: ${{ env.BUILD_SHA }}

  build-image-one:
    if: ${{ (needs.changes.outputs.images == 'true') || (inputs.force == true) }}
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Build Image One
        run: |
          echo Running Build Image one
          echo TAG: ${{ env.BUILD_SHA }}
