name: Reusable Workflow with Input

on:
  workflow_call:
    inputs:
      sha:
        description: 'SHA ref to build'
        required: true
        type: string
      base_sha:
        description: 'Base SHA for diff (optional)'
        required: false
        type: string
      force:
        description: 'Force build images'
        required: false
        default: false
        type: boolean

env:
  BUILD_SHA: ${{ inputs.sha }}
  BASE_SHA: ${{ inputs.base_sha }}

jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      images: ${{ steps.filter.outputs.images }}
      mtellb: ${{ steps.filter.outputs.metallb }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BUILD_SHA }}
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: .github/filters.yml
          base: "origin/master"

  build-image-one:
    if: ${{ (needs.changes.outputs.images == 'true') || (inputs.force == true) }}
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Build Image One
        run: |
          echo Running Build Image one
