name: WORKFLOW RUN TEST (follower)

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'SHA ref to build'
        required: true
        type: string
  workflow_run:
    workflows: [ "WORKFLOW RUN TEST (initiator)" ]
    branches: [ master ]
    types:
      - completed
  workflow_call:
    inputs:
      sha:
        description: 'SHA ref to build'
        required: true
        type: string

jobs:
  display-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Display vars
        run: |
          echo "Run step from WORKFLOW RUN TEST (follower)"
          echo "Event is: ${{ github.event_name }}"
          echo "GITHUB_SHA ${{ github.sha }}"
          echo SHA_INITIATOR: "${{ github.event.workflow_run.head_sha }}"
          echo "Finish"
          echo "MY_VAR=${{ needs.set-variables.outputs.commit_sha }}"
  
  show-payload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJson(github) }}'

  reusable-workflow:
    name: Reusable workflow
    uses: ./.github/workflows/workflow_run_03.yml
    with:
      sha: ${{ github.sha }}
