name: Reusable Workflow with Input

on:
  workflow_call:
    inputs:
      sha:
        description: 'SHA ref to build'
        required: true
        default: false
        type: string

env:
  BUILD_SHA: ${{ inputs.sha }}

jobs:

#   first-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Running step
#         run: |
#           echo BUILD_SHA: ${{ env.BUILD_SHA }}

  get-before-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BUILD_SHA }}
          fetch-depth: 2

      - name: Get parent (before) commit SHA
        id: get-before
        run: |
          BEFORE=$(git rev-parse "${{ github.event.workflow_run.head_sha }}^")
          echo "Before SHA: $BEFORE"
          echo "before_sha=$BEFORE" >> $GITHUB_OUTPUT

  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      images: ${{ steps.filter.outputs.images }}
      mtellb: ${{ steps.filter.outputs.metallb }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BUILD_SHA }}

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: .github/filters.yml
