name: Reusable Workflow with Input

on:
  workflow_call:
    inputs:
      # before-sha:
      #   description: 'SHA of the preivous commit'
      #   required: true
      #   type: string
      sha:
        description: 'SHA ref to build'
        required: true
        default: false
        type: string

env:
  BUILD_SHA: ${{ inputs.sha }}

jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      images: ${{ steps.filter.outputs.images }}
      mtellb: ${{ steps.filter.outputs.metallb }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BUILD_SHA }}
          fetch-depth: 2

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: .github/filters.yml
          # ref: ${{ inputs.before-sha }}
