name: WORKFLOW RUN TEST (follower)

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "WORKFLOW RUN TEST (initiator)" ]
    branches: [ master ]
    types:
      - completed
  push:
    branches:
      - 'master'

jobs:
  run-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Run step
        run: |
          echo "Run step from WORKFLOW RUN TEST (follower)"
