name: WORKFLOW RUN TEST (initiator)

on:
  # pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'master'

env:
  BUILD_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha}}
  RUN_TASK: 'false'

jobs:
  first-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Running step
        run: |
          echo "Welcome to the machine"
          echo "Event is: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "PULL SHA: ${{ github.event.pull_request.head.sha }}"
          echo "PUSH SHA: ${{ github.event.push.head.sha }}"
          echo "BUILD_SHA: ${{ env.BUILD_SHA }}"
          echo "==="
          echo "Before: ${{ github.event.before }}"
          echo "After: ${{ github.event.after}}"
          echo "==="

  reusable-workflow:
    name: Reusable workflow
    uses: ./.github/workflows/workflow_run_02.yml
    with:
      sha: ${{ github.sha }}

  show-payload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJson(github) }}'
